import express from "express";
import cors from "cors";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import { pinoHttp } from "pino-http";
import { allowedOrigins } from "./config/env.js";
import { authRouter } from "./modules/auth/routes.js";
import { devicesRouter } from "./modules/devices/routes.js";
import { locationsRouter } from "./modules/locations/routes.js";
import { deviceLocationsRouter } from "./modules/locations/device-routes.js";
import { dashboardRouter } from "./modules/dashboard/routes.js";
import { usersRouter } from "./modules/users/routes.js";
import { officesRouter } from "./modules/offices/routes.js";
import { errorHandler, notFound } from "./middleware/error.js";
export const app=express();
app.set("trust proxy",1);app.disable("etag");app.use(pinoHttp());app.use(helmet());app.use(cors({origin:allowedOrigins,credentials:true,methods:["GET","POST","PATCH","DELETE"]}));app.use(express.json({limit:"1mb"}));app.use("/api",(_req,res,next)=>{res.setHeader("Cache-Control","no-store");next();});
app.get("/health",(_req,res)=>res.json({status:"ok",time:new Date().toISOString()}));
app.use("/api/auth/login",rateLimit({windowMs:15*60_000,limit:10,standardHeaders:"draft-7",legacyHeaders:false}));
app.use("/api/locations",rateLimit({windowMs:60_000,limit:300,standardHeaders:"draft-7",legacyHeaders:false}));
app.use("/api/auth",authRouter);app.use("/api/devices",devicesRouter);app.use("/api/locations",locationsRouter);app.use("/api/devices",deviceLocationsRouter);app.use("/api/dashboard",dashboardRouter);app.use("/api/users",usersRouter);app.use("/api/offices",officesRouter);app.use(notFound);app.use(errorHandler);
