import "dotenv/config";
import http from "node:http";
import { Server } from "socket.io";
import { app } from "./app.js";
import { allowedOrigins, env } from "./config/env.js";
import { prisma } from "./config/db.js";
import { runRetentionCleanup } from "./services/retention.js";
import { broadcast, configureSockets } from "./sockets/index.js";
import { getStatus } from "./utils/status.js";
const httpServer=http.createServer(app);const io=new Server(httpServer,{cors:{origin:allowedOrigins,credentials:true}});configureSockets(io);
const known=new Map<string,string>();setInterval(async()=>{const devices=await prisma.device.findMany({select:{id:true,lastSeenAt:true}});for(const d of devices){const s=getStatus(d.lastSeenAt),old=known.get(d.id);if(old&&old!==s)broadcast(s==="OFFLINE"?"device:offline":s==="ONLINE"?"device:online":"device:updated",{deviceId:d.id,status:s});known.set(d.id,s);}},30000).unref();
setInterval(()=>{runRetentionCleanup().catch(error=>console.error("Retention cleanup failed",error));},24*60*60_000).unref();
httpServer.listen(env.PORT,()=>console.log(`LiveTrack API listening on ${env.PORT}`));
const shutdown=async()=>{io.close();httpServer.close();await prisma.$disconnect();process.exit(0)};process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);
